### PR TITLE
fix: do not escape at the start of line

### PR DESCRIPTION
**Pull request by telemachus**

### CODE REVIEW

**Comment by telemachus** [comment]
While working on [the multibyte option](https://github.com/m4xshen/autoclose.nvim/issues/41), I think I discovered a bug.

Steps to reproduce:

+ Enter `'` or `"` (or any other pair where the first and second items are identical) while in insert or command mode.
+ Move to the start of the line and enter the same character again.
+ Instead of entering the new character (and possibly a closing second character), you will end up escaping and jumping over the existing `'` or `"`.

I think that this is unintended behavior. (Compare `(`, for example, or any other pair where the two characters are not identical.) If not, go ahead and close this PR.

**Comment by m4xshen** [comment]
> I think that this is unintended behavior. (Compare `(`, for example, or any other pair where the two characters are not identical.)

I see. But the escape of the first quote not only happens at the start of line. If you only fix this behavior at the start of line, it would be different from the behavior at other positions, which might be confusing for users.

**Comment by telemachus** [comment]
> But the escape of the first quote not only happens at the start of line. If you only fix this behavior at the start of line, it would be different from the behavior at other positions, which might be confusing for users.

Ah, okay. I didn't realize that the behavior was the same everywhere. I guess the next questions are (1) Is this behavior intentional? and (2) If it's not intentional, how badly do you want to change the current behavior? That is, maybe this is a corner case that people will not run into often. Feel free to close this if you'd rather leave things as they are.

**Comment by m4xshen** [comment]
This is not intentional but I want to keep the current behavior.

**Pull request closed without merging**
